--- 
services: 
  - 
    dockerfilePath: Dockerfile
    envs: 
      - 
        key: REDIS_LINK
        type: SECRET
        value: "TEST VALUE"
      - 
        key: REDIS_PORT
        type: SECRET
        value: ~
      - 
        key: XYZ
        value: ~
    git: 
      branch: master
      repoCloneUrl: "https://github.com/nicolasff/webdis.git"
    http_port: 7379
    name: webdis
    routes: 
      - 
        path: /
